file=open("file3.txt","w")
file.write("This is the tree\n This is the house\n ")
file.close()
file=open("file3.txt","r")
data=file.read()
a=data.split()
b=a.count("the")
print("No. Of times'the' comes:",b)
file.close()